# Generated by Django 5.2.5 on 2025-09-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk']},
        ),
    ]
