# Generated by Django 5.2.5 on 2025-09-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['pk']},
        ),
    ]
