# Generated by Django 5.2.5 on 2025-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_taskslabels_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks_with_labels', through='tasks.TasksLabels', to='labels.label'),
        ),
    ]
