# Generated by Django 5.2.5 on 2025-09-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['pk']},
        ),
    ]
