# Generated by Django 5.2.5 on 2025-09-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_labels_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
